inherit_from:
  - .ruby-style.yml

AllCops:
  Exclude:
    - "bin/*"
    - "vendor/**/*"
    - "gemfiles/**/*"
    - "spec/rails/**/*"
    - "lib/generators/active_admin_role/templates/**/*"
    - Gemfile
    - Rakefile
  DisplayCopNames: true
  TargetRubyVersion: 2.1

Metrics/LineLength:
  Enabled: false
